import { SupabaseRest } from './supabase';

type AuthEnv = { SUPABASE_URL:string; SUPABASE_ANON_KEY?:string; SUPABASE_SERVICE_ROLE_KEY:string; OPERATOR_API_KEY:string; ENVIRONMENT?:string; BUILD_COMMIT?:string; SCHEMA_VERSION?:string };
export type Principal = { kind:'service'|'user'; userId:string|null; email:string|null; platformRole:string|null };
const PLATFORM_ROLES=new Set(['platform_admin','platform_operator','platform_reviewer','support']);
const WORKSPACE_PERMISSIONS:Record<string,Set<string>>={owner:new Set(['workspace:read','workspace:manage','run:start','review:write','report:publish','experiment:write']),operator:new Set(['workspace:read','run:start','review:write','report:publish','experiment:write']),reviewer:new Set(['workspace:read','review:write','report:read']),viewer:new Set(['workspace:read','report:read'])};

export async function authenticatePrincipal(request:Request,env:AuthEnv,db:SupabaseRest):Promise<Principal|null>{
  const token=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'')??'';if(!token)return null;
  if(constantTimeEqual(token,env.OPERATOR_API_KEY))return{kind:'service',userId:null,email:null,platformRole:'platform_admin'};
  const response=await fetch(`${env.SUPABASE_URL.replace(/\/$/,'')}/auth/v1/user`,{headers:{Authorization:`Bearer ${token}`,apikey:env.SUPABASE_ANON_KEY??env.SUPABASE_SERVICE_ROLE_KEY}});if(!response.ok)return null;
  const user=await response.json() as {id?:string;email?:string};if(!user.id)return null;
  const roles=await db.select<{role:string;revoked_at:string|null}>('platform_members',`user_id=eq.${encodeURIComponent(user.id)}&select=role,revoked_at&limit=1`);
  const role=roles[0]&&!roles[0].revoked_at&&PLATFORM_ROLES.has(roles[0].role)?roles[0].role:null;return{kind:'user',userId:user.id,email:user.email??null,platformRole:role};
}
export function canUsePlatformApi(principal:Principal,operation:'read'|'review'|'mutate'){if(principal.kind==='service'||principal.platformRole==='platform_admin')return true;if(operation==='read')return['platform_operator','platform_reviewer','support'].includes(principal.platformRole??'');if(operation==='review')return['platform_operator','platform_reviewer'].includes(principal.platformRole??'');return principal.platformRole==='platform_operator';}
export async function requireWorkspacePermission(db:SupabaseRest,principal:Principal,workspaceId:string,permission:string){if(principal.kind==='service'||principal.platformRole==='platform_admin'||principal.platformRole==='platform_operator')return{role:principal.platformRole??'service'};if(!principal.userId)throw forbidden('workspace membership required');const rows=await db.select<{role:string}>('workspace_members',`workspace_id=eq.${encodeURIComponent(workspaceId)}&user_id=eq.${encodeURIComponent(principal.userId)}&select=role&limit=1`);const role=rows[0]?.role;if(!role||!WORKSPACE_PERMISSIONS[role]?.has(permission))throw forbidden('insufficient workspace role');return{role};}
export async function recordAuthorizationEvent(db:SupabaseRest,input:{principal:Principal|null;workspaceId?:string|null;action:string;outcome:string;correlationId:string;metadata?:Record<string,unknown>}){await db.insert('authorization_events',{workspace_id:input.workspaceId??null,user_id:input.principal?.userId??null,principal_type:input.principal?.kind??'anonymous',platform_role:input.principal?.platformRole??null,action:input.action,outcome:input.outcome,correlation_id:input.correlationId,metadata:sanitize(input.metadata??{})});}
export async function getPilotConsole(db:SupabaseRest,principal:Principal,workspaceId:string){await requireWorkspacePermission(db,principal,workspaceId,'workspace:read');const[brands,runs,review,reports,interventions,verifications]=await Promise.all([db.select<any>('brands',`workspace_id=eq.${encodeURIComponent(workspaceId)}&select=id,name,domain`),db.select<any>('audit_runs',`workspace_id=eq.${encodeURIComponent(workspaceId)}&select=id,state,actual_cost_micros,created_at&order=created_at.desc&limit=20`),db.select<any>('audit_run_items',`workspace_id=eq.${encodeURIComponent(workspaceId)}&state=eq.review_required&select=id,audit_run_id`),db.select<any>('report_drafts',`workspace_id=eq.${encodeURIComponent(workspaceId)}&select=id,title,state,updated_at&order=updated_at.desc&limit=20`),db.select<any>('interventions',`workspace_id=eq.${encodeURIComponent(workspaceId)}&select=id,title,state,due_at&order=created_at.desc&limit=20`),db.select<any>('pilot_verifications',`workspace_id=eq.${encodeURIComponent(workspaceId)}&select=id,status,environment,commit_sha,created_at&order=created_at.desc&limit=5`)]);return{workspaceId,brands,runs,reviewBacklog:review.length,reports,interventions,verifications};}
export function renderPilotConsole(data:any){const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));const cards=[['Brands',data.brands.length],['Recent runs',data.runs.length],['Review backlog',data.reviewBacklog],['Reports',data.reports.length],['Interventions',data.interventions.length]].map(([label,value])=>`<article><strong>${esc(value)}</strong><span>${esc(label)}</span></article>`).join('');const rows=data.runs.map((run:any)=>`<tr><td>${esc(run.id)}</td><td>${esc(run.state)}</td><td>${esc(Number(run.actual_cost_micros??0)/1_000_000)}</td></tr>`).join('');return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Citely Pilot Console</title><style>body{font:15px system-ui;margin:0;background:#f4f7f8;color:#102a2e}header{padding:24px;background:#092f35;color:white}main{max-width:1100px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}article,section{background:white;border:1px solid #d9e4e6;border-radius:12px;padding:18px}article strong{font-size:28px;display:block}article span{color:#52686b}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{text-align:left;padding:10px;border-bottom:1px solid #e5ecee}</style></head><body><header><h1>Citely Pilot Console</h1><p>Workspace ${esc(data.workspaceId)}</p></header><main><div class="grid">${cards}</div><section><h2>Recent audit runs</h2><table><thead><tr><th>Run</th><th>State</th><th>Cost (USD)</th></tr></thead><tbody>${rows}</tbody></table></section><section><h2>Operational status</h2><p>Latest verification: ${esc(data.verifications[0]?.status??'not run')}</p></section></main></body></html>`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'private, no-store','x-content-type-options':'nosniff','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'"}});}
export function deploymentHealth(env:AuthEnv){return{ok:true,service:'citely-phase4',environment:env.ENVIRONMENT??'local',commit:env.BUILD_COMMIT??'unknown',schemaVersion:env.SCHEMA_VERSION??'unknown'};}
function constantTimeEqual(actual:string,expected:string){if(!actual||!expected||actual.length!==expected.length)return false;let mismatch=0;for(let index=0;index<actual.length;index+=1)mismatch|=actual.charCodeAt(index)^expected.charCodeAt(index);return mismatch===0;}
function forbidden(message:string){const error=new Error(message) as Error&{status:number};error.status=403;return error;}
function sanitize(value:unknown):unknown{if(Array.isArray(value))return value.map(sanitize);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([key,item])=>[key,/token|secret|authorization|raw_response|answer_text/i.test(key)?'[REDACTED]':sanitize(item)]));return value;}
