import { SupabaseRest } from './supabase';

export async function buildWorkspaceSourceGraph(db:SupabaseRest,workspaceId:string,body:any){
  const consent=await db.select<any>('data_processing_consents',`workspace_id=eq.${encodeURIComponent(workspaceId)}&purpose=eq.source_graph&status=eq.granted&select=id,expires_at,withdrawn_at&limit=1`);
  if(!consent[0]||consent[0].withdrawn_at||consent[0].expires_at&&new Date(consent[0].expires_at).getTime()<=Date.now())throw forbidden('active source graph consent is required');
  if(!Array.isArray(body.reportVersionIds)||!body.reportVersionIds.length)throw bad('reportVersionIds are required');
  const nodes=new Map<string,any>(),edges=new Map<string,any>();let methodologyFingerprint=body.methodologyFingerprint??null;
  for(const reportVersionId of body.reportVersionIds){
    const version=await db.one<any>('report_versions',`id=eq.${encodeURIComponent(reportVersionId)}&select=id,report_draft_id,snapshot`);
    await db.one<any>('report_drafts',`id=eq.${encodeURIComponent(version.report_draft_id)}&workspace_id=eq.${encodeURIComponent(workspaceId)}&state=eq.published&select=id`);
    methodologyFingerprint??=await hashJson(version.snapshot.methodology??{});
    for(const evidence of version.snapshot.evidence??[]){const provider=evidence.provider?.name??'unknown';for(const[kind,items]of[['inline_citation',evidence.citations??[]],['retrieved',evidence.sources??[]]] as const)for(const item of items){const domain=normalizedDomain(item.domain??item.url);if(!domain)continue;const node=nodes.get(domain)??{domain,inlineCitations:0,retrievedSources:0,providers:new Set<string>(),ownership:{}};if(kind==='inline_citation')node.inlineCitations++;else node.retrievedSources++;node.providers.add(provider);node.ownership[item.ownership??'unknown']=(node.ownership[item.ownership??'unknown']??0)+1;nodes.set(domain,node);const key=`${provider}|${domain}|${kind}`;edges.set(key,{provider,domain,kind,count:(edges.get(key)?.count??0)+1});}}
  }
  const graph={schemaVersion:1,nodes:[...nodes.values()].map((node)=>({...node,providers:[...node.providers].sort(),providerDependent:node.providers.size===1})).sort((a,b)=>a.domain.localeCompare(b.domain)),edges:[...edges.values()].sort((a,b)=>`${a.provider}${a.domain}${a.kind}`.localeCompare(`${b.provider}${b.domain}${b.kind}`)),reportCount:body.reportVersionIds.length,generatedAt:new Date().toISOString()};
  const fingerprint=await hashJson({...graph,generatedAt:undefined});const scopeKey=`workspace:${workspaceId}`;const existing=await db.select<any>('source_graph_snapshots',`fingerprint=eq.${fingerprint}&select=id&limit=1`);if(existing[0])return{sourceGraphId:existing[0].id,reused:true,graph};const[row]=await db.insert<any>('source_graph_snapshots',{scope_key:scopeKey,methodology_fingerprint:methodologyFingerprint,fingerprint,graph,status:'published'});await db.insert('processing_events',{workspace_id:workspaceId,purpose:'source_graph',event_type:'source_graph.published',resource_type:'source_graph_snapshot',resource_id:row.id,actor_type:'service',correlation_id:body.correlationId??crypto.randomUUID(),metadata:{reportCount:body.reportVersionIds.length}});return{sourceGraphId:row.id,reused:false,graph};
}
export async function getWorkspaceSourceGraph(db:SupabaseRest,workspaceId:string){const consent=await db.select<any>('data_processing_consents',`workspace_id=eq.${encodeURIComponent(workspaceId)}&purpose=eq.source_graph&status=eq.granted&select=id&limit=1`);if(!consent[0])return{available:false,reason:'consent_required'};const rows=await db.select<any>('source_graph_snapshots',`scope_key=eq.${encodeURIComponent(`workspace:${workspaceId}`)}&status=eq.published&select=id,graph,generated_at&order=generated_at.desc&limit=1`);return rows[0]?{available:true,sourceGraphId:rows[0].id,generatedAt:rows[0].generated_at,graph:rows[0].graph}:{available:false,reason:'no_published_graph'};}
function normalizedDomain(value:unknown){try{return new URL(String(value).includes('://')?String(value):`https://${String(value)}`).hostname.replace(/^www\./,'').toLowerCase();}catch{return null;}}
async function hashJson(value:unknown){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(sortValue(value))));return[...new Uint8Array(bytes)].map((byte)=>byte.toString(16).padStart(2,'0')).join('');}
function sortValue(value:any):any{if(Array.isArray(value))return value.map(sortValue).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).filter((key)=>value[key]!==undefined).sort().map((key)=>[key,sortValue(value[key])]));return value;}
function bad(message:string){const error=new Error(message) as Error&{status:number};error.status=400;return error;}function forbidden(message:string){const error=new Error(message) as Error&{status:number};error.status=403;return error;}
