/**
 * Stable non-cryptographic identifier for idempotency and fixtures.
 * Security-sensitive identifiers must continue to use UUIDs generated by the store/database.
 */
export function stableKey(...parts) {
  const input = parts.map(canonicalPart).join('\u001f');
  let high = 0x811c9dc5;
  let low = 0x01000193;
  for (let index = 0; index < input.length; index += 1) {
    const code = input.charCodeAt(index);
    high ^= code;
    high = Math.imul(high, 0x01000193) >>> 0;
    low ^= code + index;
    low = Math.imul(low, 0x85ebca6b) >>> 0;
  }
  return `${high.toString(16).padStart(8, '0')}${low.toString(16).padStart(8, '0')}`;
}

export function observationKey({ auditRunId, promptVersionId, providerProfileId, repetition }) {
  if (!auditRunId || !promptVersionId || !providerProfileId || !Number.isInteger(repetition) || repetition < 1) {
    throw new Error('Cannot build observation key from incomplete identifiers');
  }
  return `obs_${stableKey(auditRunId, promptVersionId, providerProfileId, repetition)}`;
}

function canonicalPart(value) {
  if (value === null) return 'null';
  if (value === undefined) return 'undefined';
  if (typeof value === 'object') return stableStringify(value);
  return String(value);
}

export function stableStringify(value) {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`;
  if (value && typeof value === 'object') {
    return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`).join(',')}}`;
  }
  return JSON.stringify(value);
}
